INSERT INTO tb_user (name, email, password) VALUES ('Bob Brown', 'bob@gmail.com', '$2a$10$eACCYoNOHEqXve8aIWT8Nu3PkMXWBaOxJ9aORUYzfMQCbVBIhZ8tG');
INSERT INTO tb_user (name, email, password) VALUES ('Ana Grey', 'ana@gmail.com', '$2a$10$eACCYoNOHEqXve8aIWT8Nu3PkMXWBaOxJ9aORUYzfMQCbVBIhZ8tG');

INSERT INTO tb_role (authority) VALUES ('ROLE_VISITOR');
INSERT INTO tb_role (authority) VALUES ('ROLE_MEMBER');

INSERT INTO tb_user_role (user_id, role_id) VALUES (1, 1);
INSERT INTO tb_user_role (user_id, role_id) VALUES (2, 2);

INSERT INTO tb_genre (name) VALUES ('Ação');
INSERT INTO tb_genre (name) VALUES ('Animação');
INSERT INTO tb_genre (name) VALUES ('Aventura');
INSERT INTO tb_genre (name) VALUES ('Drama');
INSERT INTO tb_genre (name) VALUES ('Ficção científica');
INSERT INTO tb_genre (name) VALUES ('Terror');

INSERT INTO tb_movie (title, sub_Title, year, img_Url, synopsis, genre_id) VALUES ('Mulher-Maravilha 1984', 'Uma nova era de maravilhas começa.', 2020, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/srYya1ZlI97Au4jUYAktDe3avyA.jpg', 'Em 1984, Diana Prince entra em conflito com dois inimigos formidáveis, Maxwell Lord e a Mulher-Leopardo, enquanto reencontra misteriosamente com seu antigo interesse amoroso Steve Trevor.', 1);
INSERT INTO tb_movie (title, sub_Title, year, img_Url, synopsis, genre_id) VALUES ('Demon Slayer: O Trem Infinito', 'Com sua lâmina, dê um fim ao pesadelo.', 2020, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/d1sVANghKKMZNvqjW0V6y1ejvV9.jpg', 'Tanjiro Kamado, junto com Inosuke Hashibira, um garoto criado por javalis que usa uma cabeça de javali, e Zenitsu Agatsuma, um garoto assustado que revela seu verdadeiro poder quando dorme, embarca no Trem Infinito em uma nova missão com o Hashira de Fogo, Kyojuro Rengoku, para derrotar um demônio que tem atormentado o povo e matado os caçadores de oni que se opõem a ele!', 2);
INSERT INTO tb_movie (title, sub_Title, year, img_Url, synopsis, genre_id) VALUES ('Godzilla vs. Kong', 'Um dos dois cairá.', 2021, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/inJjDhCjfhh3RtrJWBmmDqeuSYC.jpg', 'Em uma época em que os monstros andam na Terra, a luta da humanidade por seu futuro coloca Godzilla e Kong em rota de colisão que verá as duas forças mais poderosas da natureza no planeta se confrontarem em uma batalha espetacular para as idades. Enquanto Monarch embarca em uma missão perigosa em terreno desconhecido e descobre pistas sobre as origens dos Titãs, uma conspiração humana ameaça tirar as criaturas, boas e más, da face da terra para sempre.', 5);
INSERT INTO tb_movie (title, sub_Title, year, img_Url, synopsis, genre_id) VALUES ('Projeto Gemini', 'Quem pode salvá-lo de você mesmo.', 2019, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/c3F4P2oauA7IQmy4hM0OmRt2W7d.jpg', 'Henry Brogan é um assassino de elite que se torna o alvo de um agente misterioso que aparentemente pode prever todos os seus movimentos. Ele logo descobre que o homem que está tentando matá-lo é uma versão mais jovem, rápida e clonada de si mesmo.', 5);
INSERT INTO tb_movie (title, sub_Title, year, img_Url, synopsis, genre_id) VALUES ('Coringa', 'Coloque um sorriso nessa cara.', 2019, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/n6bUvigpRFqSwmPp1m2YADdbRBc.jpg', 'Arthur Fleck trabalha como palhaço para uma agência de talentos e, toda semana, precisa comparecer a uma agente social, devido aos seus conhecidos problemas mentais. Após ser demitido, Fleck reage mal à gozação de três homens em pleno metrô e os mata. Os assassinatos iniciam um movimento popular contra a elite de Gotham City, da qual Thomas Wayne é seu maior representante.', 4);
INSERT INTO tb_movie (title, sub_Title, year, img_Url, synopsis, genre_id) VALUES ('Vingadores: Ultimato', 'O fim de uma era!', 2019, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/7RyHsO4yDXtBv1zUU3mTpHeQ0d5.jpg', 'Após os eventos devastadores de "Vingadores: Guerra Infinita", o universo está em ruínas devido aos esforços do Titã Louco, Thanos. Com a ajuda de aliados remanescentes, os Vingadores devem se reunir mais uma vez a fim de desfazer as ações de Thanos e restaurar a ordem no universo de uma vez por todas, não importando as consequências.', 3);
INSERT INTO tb_movie (title, sub_Title, year, img_Url, synopsis, genre_id) VALUES ('It - A Coisa', 'Você Também vai Flutuar.', 2017, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/9IHPpCSAmP4KO3gCq7GpgFjVKcy.jpg', 'Um grupo de sete adolescentes de Derry, uma cidade no Maine, formam o auto-intitulado "Losers Club", o clube dos perdedores. A pacata rotina da cidade é abalada quando crianças começam a desaparecer e tudo o que pode ser encontrado delas são partes de seus corpos. Logo, os integrantes do "Losers Club" acabam ficando face a face com o responsável pelos crimes: o palhaço Pennywise.', 6);
INSERT INTO tb_movie (title, sub_Title, year, img_Url, synopsis, genre_id) VALUES ('It: Capítulo Dois', 'Você Vai Flutuar de Novo', 2019, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/8moTOzunF7p40oR5XhlDvJckOSW.jpg', 'Vinte e sete anos depois dos eventos que chocaram os adolescentes que faziam parte do Clube dos Perdedores, os amigos realizam uma reunião. No entanto, o reencontro se torna uma verdadeira e sangrenta batalha quando Pennywise, o palhaço, retorna.', 6);
INSERT INTO tb_movie (title, sub_Title, year, img_Url, synopsis, genre_id) VALUES ('O Iluminado', 'Ele veio como zelador, mas este hotel tinha seus próprios guardiões, que estavam lá há muito tempo.', 1980, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/mmd1HnuvAzFc4iuVJcnBrhDNEKr.jpg', 'Durante o inverno, um homem é contratado para ficar como vigia em um hotel no Colorado e vai para lá com a mulher e seu filho. Porém, o contínuo isolamento começa a lhe causar sérios problemas mentais e ele vai se tornado cada vez mais agressivo e perigoso, ao mesmo tempo que seu filho passa a ter visões de acontecimentos ocorridos no passado, que também foram causados pelo isolamento excessivo.', 6);
INSERT INTO tb_movie (title, sub_Title, year, img_Url, synopsis, genre_id) VALUES ('Doutor Sono', 'Atreva-se a voltar.', 2019, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/ap6Zc5NDOfbZaMhkRDyghbGeLf0.jpg', 'Na infância, Danny Torrance conseguiu sobreviver a uma tentativa de homicídio por parte do pai, um escritor perturbado por espíritos malignos. Danny cresceu, agora ele é um adulto traumatizado e alcoólatra. Sem residência fixa, ele se estabelece em uma pequena cidade, onde consegue um emprego no hospício local e cria um vínculo telepático com uma menina, paciente da instituição.', 6);
INSERT INTO tb_movie (title, sub_Title, year, img_Url, synopsis, genre_id) VALUES ('Jogador N° 1', 'Uma aventura muito além do mundo real.', 2018, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/5a7lMDn3nAj2ByO0X1fg6BhUphR.jpg', 'Num futuro distópico, situado em 2044, Wade Watts, como o resto da humanidade, prefere a realidade virtual do jogo OASIS ao mundo real. No jogo, seus usuários devem descobrir a chave de um quebra-cabeça diabólico, baseado na cultura do final do século XX, para conquistar um prêmio de valor inestimável. Para vencê-lo, porém, Watts terá de abandonar a existência virtual e ceder a uma vida de amor e realidade da qual sempre tentou fugir.', 5);
INSERT INTO tb_movie (title, sub_Title, year, img_Url, synopsis, genre_id) VALUES ('John Wick 3: Parabellum', 'Toda ação tem uma consequência.', 2019, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/vVpEOvdxVBP2aV166j5Xlvb5Cdc.jpg', 'Após assassinar o chefe da máfia Santino D''Antonio no Hotel Continental, John Wick passa a ser perseguido pelos membros da Alta Cúpula sob a recompensa de U$14 milhões. Agora, ele precisa unir forças com antigos parceiros que o ajudaram no passado enquanto luta por sua sobrevivência.', 1);
INSERT INTO tb_movie (title, sub_Title, year, img_Url, synopsis, genre_id) VALUES ('Espiral - O Legado de Jogos Mortais', 'Descubra um novo capítulo.', 2021, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/4JoR5107gSdOK1ICzvWikpIp2Vz.jpg', 'Sob o comando do veterano da polícia Marcus, o detetive Ezekiel "Zeke" Banks se une ao seu parceiro novato Willem para desvendar uma série de assassinatos terríveis que estão acontecendo na cidade. Durante as investigações, Zeke acaba se envolvendo no mórbido jogo do assassino.', 6);
INSERT INTO tb_movie (title, sub_Title, year, img_Url, synopsis, genre_id) VALUES ('Mortal Kombat', 'Get over here.', 2021, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/9yBVqNruk6Ykrwc32qrK2TIE5xw.jpg', 'Nova aventura baseada no videogame Mortal Kombat. Na história, um jovem que nunca treinou artes marciais acaba envolvido em um gigantesco torneio de luta envolvendo guerreiros da Terra e lutadores e outras dimensões.', 1);
INSERT INTO tb_movie (title, sub_Title, year, img_Url, synopsis, genre_id) VALUES ('Operação Big Hero', 'Prepare-se para ação.', 2014, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/4s2d3xdyqotiVNHTlTlJjrr3q0H.jpg', 'O grande robô inflável está sempre a postos para cuidar de Hiro Hamada. Quando algo devastador assola a cidade, o menino prodígio, seus amigos e o robô formam um grupo de heróis para combater o mal.', 2);
INSERT INTO tb_movie (title, sub_Title, year, img_Url, synopsis, genre_id) VALUES ('Doutor Estranho', 'As impossibilidades são infinitas.', 2016, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/eQN31P4IEhyp6NkdccvppJnyuJ4.jpg', 'Da Marvel Studios vem “Doctor Strange”, a história do mundialmente famoso neurocirurgião Dr. Stephen Strange, cuja vida muda para sempre depois de um terrível acidente de carro, que o rouba do uso de suas mãos. Quando a medicina tradicional o falha, ele é forçado a procurar por cura e esperança, em um lugar improvável - um enclave misterioso conhecido como Kamar-Taj. Ele rapidamente descobre que isso não é apenas um centro de cura, mas também a linha de frente de uma batalha contra as forças ocultas invisíveis empenhadas em destruir nossa realidade. Em pouco tempo, Strange - armado com poderes mágicos recém-adquiridos - é forçado a escolher se quer retornar à sua vida de fortuna e status ou deixar tudo para trás para defender o mundo como o mais poderoso feiticeiro existente.', 3);
INSERT INTO tb_movie (title, sub_Title, year, img_Url, synopsis, genre_id) VALUES ('Homem-Aranha: De Volta ao Lar', 'O dever de casa pode esperar. A cidade não.', 2017, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/vMNEvp4wKAkDIODZjz5BsqVWY9y.jpg', 'Depois de atuar ao lado dos Vingadores, chegou a hora do pequeno Peter Parker (Tom Holland) voltar para casa e para a sua vida, já não mais tão normal. Lutando diariamente contra pequenos crimes nas redondezas, ele pensa ter encontrado a missão de sua vida quando o terrível vilão Abutre (Michael Keaton) surge amedrontando a cidade. O problema é que a tarefa não será tão fácil como ele imaginava.', 3);
INSERT INTO tb_movie (title, sub_Title, year, img_Url, synopsis, genre_id) VALUES ('Homem-Aranha: Longe de Casa', 'Continuar é preciso.', 2019, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/tq6yTPDmM8f5IMEiCyy9GgzX07G.jpg', 'Peter Parker está em uma viagem de duas semanas pela Europa, ao lado de seus amigos de colégio, quando é surpreendido pela visita de Nick Fury. Convocado para mais uma missão heroica, ele precisa enfrentar vários vilões que surgem em cidades-símbolo do continente, como Londres, Paris e Veneza, e também a aparição do enigmático Mysterio.', 3);
INSERT INTO tb_movie (title, sub_Title, year, img_Url, synopsis, genre_id) VALUES ('Parasita', 'Aja como se fosse o dono do lugar.', 2019, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/cI1RBfqXbWaITTjcKGYLhd9F083.jpg', 'Toda a família de Ki-taek está desempregada, vivendo num porão sujo e apertado. Uma obra do acaso faz com que o filho adolescente da família comece a dar aulas de inglês à garota de uma família rica. Fascinados com a vida luxuosa destas pessoas, pai, mãe, filho e filha bolam um plano para se infiltrarem também na família burguesa, um a um. No entanto, os segredos e mentiras necessários à ascensão social custarão caro a todos.', 4);
INSERT INTO tb_movie (title, sub_Title, year, img_Url, synopsis, genre_id) VALUES ('Monster Hunter', 'Junte-se à caçada.', 2020, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/z8TvnEVRenMSTemxYZwLGqFofgF.jpg', 'Baseado no jogo da Capcom chamado Monster Hunter, a tenente Artemis e seus soldados são transportados para um novo mundo. Lá, eles se envolvem em batalhas imponentes, buscando desesperadamente a sobrevivência contra bestas gigantes portadoras de habilidades surreais.', 1);
INSERT INTO tb_movie (title, sub_Title, year, img_Url, synopsis, genre_id) VALUES ('Invocação do Mal', 'Baseado em arquivos de uma investigação real do casal Warren.', 2013, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/mXndmCbpvlqnD6po0EMfxEZcUSn.jpg', 'Harrisville, Rhode Island, Estados Unidos, 1968. Os investigadores paranormais Ed e Lorraine Warren trabalham para ajudar uma família aterrorizada por uma presença sombria em sua fazenda. Forçados a confrontar uma entidade poderosa, os Warrens se vêem presos no caso mais aterrorizante de suas vidas. Baseado numa história real.', 6);
INSERT INTO tb_movie (title, sub_Title, year, img_Url, synopsis, genre_id) VALUES ('Invocação do Mal 2', 'A próxima história real baseada nos casos de Ed e Lorraine Warren.', 2016, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/4mfFtlGeInPrQVm1hpv7th02yjx.jpg', 'Sete anos após os eventos de Invocação do Mal (2013), Lorraine (Vera Farmiga) e Ed Warren (Patrick Wilson) desembarcam na Inglaterra para ajudar uma família atormentada por uma manifestação poltergeist na filha. A trama é baseada no caso Enfield Poltergeist, registrado no final da década de 1970.', 6);
INSERT INTO tb_movie (title, sub_Title, year, img_Url, synopsis, genre_id) VALUES ('Frozen II', 'Descubra o passado. Enfrente o futuro.', 2019, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/AoSZyb37ljMAxw0RdeQEBHKtgcc.jpg', 'De volta à infância de Elsa e Anna, as duas garotas descobrem uma história do pai, quando ainda era príncipe de Arendelle. Ele conta às meninas a história de uma visita à floresta dos elementos, onde um acontecimento inesperado teria provocado a separação dos habitantes da cidade com os quatro elementos fundamentais: ar, fogo, terra e água. Esta revelação ajudará Elsa a compreender a origem de seus poderes.', 2);
INSERT INTO tb_movie (title, sub_Title, year, img_Url, synopsis, genre_id) VALUES ('Os Mercenários 3', 'Nova equipe. Nova atitude. Nova missão.', 2014, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/sJDBJxKWG7h3VpG6jc9Mm9bw4kG.jpg', 'Barney e sua trupe de mercenários resgatam Doc, um dos integrantes do grupo, que estava preso há oito anos. Ao participarem de uma missão, os mercenários são surpreendidos quando reencontram Conrad, um comerciante de armas impiedoso, que Barney pensava ter matado. Novos membros, mais jovens e mais rápidos, entram para equipe e um novo duelo começa.', 1);
INSERT INTO tb_movie (title, sub_Title, year, img_Url, synopsis, genre_id) VALUES ('Velozes e Furiosos: Desafio em Tóquio', 'Adrenalina a cada curva!', 2006, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/eJciNVeMWekmBAeT7HrDP4DWmFb.jpg', 'Sean Boswell é um piloto de rua que desafia seu rival e bate o carro no fim da corrida. Então, Sean decide se mudar para o Japão em companhia de seu pai para evitar a prisão nos Estados Unidos, já que os rachas não são nada populares com as autoridades. Em Tóquio, ele começa a aprender um excitante e perigoso estilo novo de competir nas ruas. Só que os riscos ficam ainda mais altos quando Sean decide competir com o campeão local e acaba se apaixonando pela namorada dele.', 1);
INSERT INTO tb_movie (title, sub_Title, year, img_Url, synopsis, genre_id) VALUES ('Velozes e Furiosos: Hobbs & Shaw', 'Muita ação, adrenalina e pancadaria.', 2019, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/qAhedRxRYWZAgZ8O8pHIl6QHdD7.jpg', 'Desde que se conheceram, em "Velozes & Furiosos 7", Luke Hobbs (Dwayne Johnson) e Deckard Shaw (Jason Statham) constantemente bateram de frente, não só por inicialmente estarem em lados opostos mas, especialmente, pela personalidade de cada um. Agora, a dupla precisa unir forças para enfrentar Brixton (Idris Elba), um anarquista alterado geneticamente que se tornou uma ameaça biológica global. Para tanto, eles contam com a ajuda de Hattie (Vanessa Kirby), irmã de Shaw, que é também agente do MI6, o serviço secreto britânico.', 1);

-- INSERT INTO tb_review (text, movie_id, user_id) VALUES ('Gostei muito do filme. Foi muito bom mesmo. Pena que durou pouco', 6, 2);
-- INSERT INTO tb_review (text, movie_id, user_id) VALUES ('Gostei muito do filme. Foi muito bom mesmo. Pena que durou pouco', 6, 2);
-- INSERT INTO tb_review (text, movie_id, user_id) VALUES ('Gostei muito do filme. Foi muito bom mesmo. Pena que durou pouco', 6, 2);
-- INSERT INTO tb_review (text, movie_id, user_id) VALUES ('Gostei muito do filme. Foi muito bom mesmo. Pena que durou pouco', 6, 2);
-- INSERT INTO tb_review (text, movie_id, user_id) VALUES ('Gostei muito do filme. Foi muito bom mesmo. Pena que durou pouco', 6, 2);
-- INSERT INTO tb_review (text, movie_id, user_id) VALUES ('Gostei muito do filme. Foi muito bom mesmo. Pena que durou pouco', 6, 2);
-- INSERT INTO tb_review (text, movie_id, user_id) VALUES ('Gostei muito do filme. Foi muito bom mesmo. Pena que durou pouco', 6, 2);
-- INSERT INTO tb_review (text, movie_id, user_id) VALUES ('Gostei muito do filme. Foi muito bom mesmo. Pena que durou pouco', 6, 2);